### ISSUE TITLE
How are the easy and hard answers generated? 

### ISSUE THREAD

**Issue by lynnliu030** [snap-stanford/KGReasoning#12]
Hi, as I'm generating queries for a new dataset using the create_queries.py, I am wondering how are the easy and hard answers generated exactly? Using create_queries.py generate three answer files, fp-answers.pkl, fn-answers.pkl, and tp-answers.pkl, but how to build easy and hard answers on top of these three?

**Comment by hyren** [comment]
Hi, thanks for your interest. The easy answers will be those in tp-answers.pkl, and the hard answers will be those in fn-answers.pkl.

**Comment by lynnliu030** [comment]
Thanks for the quick response! :)
