### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by troixanhvuctham** [snap-stanford/KGReasoning#13]
Hello, currently I am trying to using your code to generate the query and answer on **my own dataset**. I succeed to generate the query and answer .pkl file, but when I run the training, it yeld the error like this 

```
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: block: [4,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.3.2\plugins\python\helpers\pydev\pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/ERCLab/Desktop/RESEARCH/Natural language processing/KGReasoning/main.py", line 449, in <module>
    main(parse_args())
  File "C:/Users/ERCLab/Desktop/RESEARCH/Natural language processing/KGReasoning/main.py", line 385, in main
    log = model.train_step(model, optimizer, train_path_iterator, args, step)
  File "C:\Users\ERCLab\Desktop\RESEARCH\Natural language processing\KGReasoning\models.py", line 591, in train_step
    positive_logit, negative_logit, subsampling_weight, _ = model(positive_sample, negative_sample, subsampling_weight, batch_queries_dict, batch_idxs_dict)
  File "C:\Users\ERCLab\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\ERCLab\Desktop\RESEARCH\Natural language processing\KGReasoning\models.py", line 196, in forward
    return self.forward_box(positive_sample, negative_sample, subsampling_weight, batch_queries_dict, batch_idxs_dict)
  File "C:\Users\ERCLab\Desktop\RESEARCH\Natural language processing\KGReasoning\models.py", line 434, in forward_box
    center_embedding, offset_embedding, _ = self.embed_query_box(batch_queries_dict[query_structure], 
  File "C:\Users\ERCLab\Desktop\RESEARCH\Natural language processing\KGReasoning\models.py", line 216, in embed_query_box
    offset_embedding = torch.zeros_like(embedding).cuda()
RuntimeError: CUDA error: device-side assert triggered
```
I have already tried with FB15k dataset but it didn't yield the error. I can not figure out what wrong happen. 
Could you give me some clue for solving that?

**Comment by hyren** [comment]
Have you manually set the number of relations and entities correctly for your new dataset? Accessing a GPU memory location that does not exist is often the cause of the error message above.

**Comment by troixanhvuctham** [comment]
Yes, I manually set the number of relations and entities in the _stats.txt_ file

**Comment by hyren** [comment]
Please check the queries you generated, whether they have some entities, relations out of the range.

**Comment by troixanhvuctham** [comment]
Thank you for your help, it help me a lot! I checked again and figure out the problem. 
Now the training process was done, but during the testing phase, it got error at this line code and the `len(hard_answer.intersection(easy_answer))` was not equal to 0. Is it my fault at data generation step?
![image](https://user-images.githubusercontent.com/21169328/138564728-670ee4a0-c042-401e-a6c4-f66713c9d7e1.png)

**Comment by hyren** [comment]
Yes, the set of easy answers should never have any overlap with the hard answers. The reason might be that there are some KG edges that exist both in the training set and validation/test set.

**Comment by troixanhvuctham** [comment]
HEllo @hyren 

Thanks for your help..!

After removing the duplicate triples from my dataset, the code seems working. However, I can only utilize 1p, 2i and 3i, for generating query. But it could not generate queries for 2p, 3p and other query structure. 
It seems like there is something wrong with the dataset which could not map the other query structures.
Would you mind telling what are the possible reasons for this problem.

Following is the screenshot of the error while generating with other query structure.

![image](https://user-images.githubusercontent.com/21169328/138584091-303aa74c-38fc-424b-a04a-2df941d77d24.png)
Thanks...

**Comment by hyren** [comment]
Sorry I do not have a good intuition why it does not work for 2p 3p on your case...

**Comment by troixanhvuctham** [comment]
Thank you, I think there are some problem with my dataset, I'll try to figure out those. 
Thank you for your help!

**Comment by troixanhvuctham** [comment]
Hi @hyren 

I have edited the error log figure in [above comment](https://github.com/snap-stanford/KGReasoning/issues/13#issuecomment-950190982) which shows the error when running with 2p, 3p and other query structures: 
`"ValueError: Sample larger than population or is negative" `

Could you please figure out from this error what could be the possible problem.

Thanks
