### ISSUE TITLE
Codes for generating queries

### ISSUE THREAD

**Issue by zhanqiuzhang** [snap-stanford/KGReasoning#2]
Hi, thanks for sharing the codes of the nice work!

Could you please release the codes for generating queries? Now I want to generate some queries in other structures but don't know how to make it.

**Comment by amayuelas** [comment]
I am also interested in the query generation process. 
Did you release the code for creating the queries? 
How do you create the queries and know the correct answers?

**Comment by hyren** [comment]
Hi, sorry for the late reply. I just uploaded the query generation code.

**Comment by himani1812** [comment]
Hi, how to generate 2p and 2i queries.
