### ISSUE TITLE
What's the difference between 'easy' and 'hard' answers?

### ISSUE THREAD

**Issue by HarrialX** [snap-stanford/KGReasoning#7]
Hi Dear Author,

Thanks for releasing this excellent work! The codes are very clean in use. But one thing unclear for me is about the dataset, since there're **easy answers** and **hard answers** for valid and test queries, and they seem to have no intersection. So what is the principle when you distinguish their difficulty? And how do you use both in evaluations (MRR and Hit@1,3,10)?

**Comment by hyren** [comment]
https://github.com/hyren/query2box/issues/3#issuecomment-673787482
